### ISSUE TITLE
Making Website

### ISSUE THREAD

**Issue by AthallahDzaki** [fdciabdul/hacktoberfest-indonesia#22]
Bolehkah saya membuat list kontributor?

**Comment by fdciabdul** [comment]
silahkan

**Comment by AthallahDzaki** [comment]
Silahkan di enable [GitHub Pages](https://pages.github.com/)nya

**Comment by fdciabdul** [comment]
> Silahkan di enable [GitHub Pages](https://pages.github.com/)nya

sudah kak , thankyou for contributing with us 
♪☆＼(^０^＼) ♪(／^-^)／☆
